[book]
title = "제주 소년의 마라톤 도전기"
authors = ["ohama"]
description = "버스 멀미하던 중학생이 마라톤 풀코스를 완주하기까지의 1년간의 일기"
language = "ko"
src = "src"

[build]
build-dir = "docs"

[output.html]
default-theme = "light"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/ohama/Run42.195"
site-url = "/Run42.195/"
